<?php

use Drupal\migrate\Plugin\migrate\destination\EntityRevision as CoreEntityRevision;
use Drupal\wbm2cm\Plugin\migrate\destination\EntityRevision;
use Drupal\workflows\Entity\Workflow;

/**
 * Implements hook_modules_installed().
 */
function wbm2cm_modules_installed(array $modules) {
  if (in_array('content_moderation', $modules)) {
    foreach (\Drupal::state()->get('moderation_workflows', []) as $workflow) {
      Workflow::create($workflow)->save();
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function wbm2cm_module_implements_alter(array &$implementations, $hook) {
  if ($hook == 'entity_presave') {
    unset($implementations['content_moderation']);
  }
  elseif ($hook == 'entity_storage_load') {
    unset($implementations['workbench_moderation']);
  }
}

function wbm2cm_migrate_destination_info_alter(array &$definitions) {
  foreach ($definitions as &$definition) {
    if ($definition['class'] == CoreEntityRevision::class) {
      $definition['class'] = EntityRevision::class;
    }
  }
}
